"""The two documents this app owns: the career profile, and the job cache.

Everything here is a frozen dataclass with explicit JSON conversion rather
than pydantic models, same choice and for the same reason as
jay-withers/gym-log's model.py: each document is written by this app and read
by this app, and what's wanted is a shape that survives being hand-edited in
the portal and round tripped, which `from_json` tolerating missing fields
gives.

Two separate documents rather than one, because they change on different
triggers and at different trust levels: `Profile` is edited by hand through
the app's UI (and seeded once from a LinkedIn export) and is irreplaceable if
lost — see terraform/main.storage.tf's `prevent_destroy`. `JobsDocument` is
entirely regenerated by the daily pipeline job and can be thrown away and
rebuilt from the job-board APIs with no lasting loss.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, replace
from datetime import date, datetime
from typing import Any

# Bumped when either shape changes incompatibly. A document from the future
# is left alone rather than overwritten — the alternative is a newer
# deployment silently discarding history it could not read.
SCHEMA_VERSION = 1


def _date_or_none(value: str | None) -> date | None:
    return date.fromisoformat(value) if value else None


@dataclass(frozen=True)
class Role:
    """One position held, as entered manually or imported from LinkedIn."""

    company: str
    title: str
    started: date
    # None means "current" — the LinkedIn export's own convention for an
    # ongoing role.
    ended: date | None = None
    location: str = ""
    employment_type: str = ""
    description: str = ""
    skills: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["started"] = self.started.isoformat()
        d["ended"] = self.ended.isoformat() if self.ended else None
        d["skills"] = list(self.skills)
        return d

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Role:
        return cls(
            company=d["company"],
            title=d["title"],
            started=date.fromisoformat(d["started"]),
            ended=_date_or_none(d.get("ended")),
            location=d.get("location", ""),
            employment_type=d.get("employment_type", ""),
            description=d.get("description", ""),
            skills=tuple(d.get("skills", ())),
        )


@dataclass(frozen=True)
class Certification:
    """One certification, as entered manually or imported from LinkedIn."""

    name: str
    issuing_org: str
    issued: date | None = None
    expires: date | None = None
    credential_id: str = ""
    credential_url: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "issuing_org": self.issuing_org,
            "issued": self.issued.isoformat() if self.issued else None,
            "expires": self.expires.isoformat() if self.expires else None,
            "credential_id": self.credential_id,
            "credential_url": self.credential_url,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Certification:
        return cls(
            name=d["name"],
            issuing_org=d.get("issuing_org", ""),
            issued=_date_or_none(d.get("issued")),
            expires=_date_or_none(d.get("expires")),
            credential_id=d.get("credential_id", ""),
            credential_url=d.get("credential_url", ""),
        )


@dataclass(frozen=True)
class JobPreferences:
    """What to look for beyond the profile itself.

    Read by matching.py alongside the profile's own titles and skills.
    Everything here is empty/False by default, which must mean "no extra
    preference", not "match nothing" — see `matching.score`'s handling of
    each field for why: an unset field is skipped rather than treated as an
    empty set to exclude everything against.
    """

    # Titles the profile hasn't necessarily held yet but would take, on top
    # of `Profile.all_titles` — e.g. the next rung up.
    desired_titles: tuple[str, ...] = ()
    desired_locations: tuple[str, ...] = ()
    remote_only: bool = False
    excluded_companies: tuple[str, ...] = ()
    # Deal-breakers, same as remote_only/excluded_companies: None means "no
    # preference", not "match nothing". A listing whose salary or location
    # can't be determined (most can't — see distance.py) is never excluded
    # on that account; there's simply nothing to check it against.
    min_salary: float | None = None
    home_location: str = "Fareham"
    max_distance_miles: float | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "desired_titles": list(self.desired_titles),
            "desired_locations": list(self.desired_locations),
            "remote_only": self.remote_only,
            "excluded_companies": list(self.excluded_companies),
            "min_salary": self.min_salary,
            "home_location": self.home_location,
            "max_distance_miles": self.max_distance_miles,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> JobPreferences:
        return cls(
            desired_titles=tuple(d.get("desired_titles", ())),
            desired_locations=tuple(d.get("desired_locations", ())),
            remote_only=d.get("remote_only", False),
            excluded_companies=tuple(d.get("excluded_companies", ())),
            min_salary=d.get("min_salary"),
            home_location=d.get("home_location", "Fareham"),
            max_distance_miles=d.get("max_distance_miles"),
        )


@dataclass(frozen=True)
class Profile:
    """The whole career profile: roles, certifications and the skills derived
    from them plus any added by hand.
    """

    roles: tuple[Role, ...] = ()
    certifications: tuple[Certification, ...] = ()
    # Skills not already implied by a role — added manually, or by the
    # LinkedIn importer from its own Skills.csv, which lists skills LinkedIn
    # has no other structured place to put.
    extra_skills: tuple[str, ...] = ()
    preferences: JobPreferences = field(default_factory=JobPreferences)

    @property
    def all_skills(self) -> tuple[str, ...]:
        """Every skill this profile carries, deduplicated, case-insensitively."""
        seen: dict[str, str] = {}
        for role in self.roles:
            for s in role.skills:
                seen.setdefault(s.lower(), s)
        for s in self.extra_skills:
            seen.setdefault(s.lower(), s)
        return tuple(seen.values())

    @property
    def all_titles(self) -> tuple[str, ...]:
        seen: dict[str, str] = {}
        for role in self.roles:
            seen.setdefault(role.title.lower(), role.title)
        return tuple(seen.values())

    def with_role(self, role: Role) -> Profile:
        return replace(self, roles=(*self.roles, role))

    def with_role_at(self, index: int, role: Role) -> Profile:
        """Return a copy with the role at `index` (in `self.roles`) replaced."""
        roles = list(self.roles)
        roles[index] = role
        return replace(self, roles=tuple(roles))

    def with_certification(self, cert: Certification) -> Profile:
        return replace(self, certifications=(*self.certifications, cert))

    def with_certification_at(self, index: int, cert: Certification) -> Profile:
        """Return a copy with the certification at `index` replaced."""
        certifications = list(self.certifications)
        certifications[index] = cert
        return replace(self, certifications=tuple(certifications))

    def with_preferences(self, preferences: JobPreferences) -> Profile:
        return replace(self, preferences=preferences)

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": SCHEMA_VERSION,
            "roles": [r.to_dict() for r in self.roles],
            "certifications": [c.to_dict() for c in self.certifications],
            "extra_skills": list(self.extra_skills),
            "preferences": self.preferences.to_dict(),
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> Profile:
        preferences = d.get("preferences")
        return cls(
            roles=tuple(Role.from_dict(r) for r in d.get("roles", ())),
            certifications=tuple(Certification.from_dict(c) for c in d.get("certifications", ())),
            extra_skills=tuple(d.get("extra_skills", ())),
            preferences=JobPreferences.from_dict(preferences) if preferences else JobPreferences(),
        )

    @classmethod
    def from_json(cls, raw: str) -> Profile:
        return cls.from_dict(json.loads(raw))


@dataclass(frozen=True)
class JobListing:
    """One job posting, normalized from whichever source fetched it."""

    source: str
    external_id: str
    title: str
    company: str
    location: str
    url: str
    description: str
    posted_date: date | None
    fetched_at: datetime
    # The source's own payload, kept for reprocessing (e.g. re-scoring with a
    # smarter matcher later) without re-fetching.
    raw_payload: dict[str, Any] = field(default_factory=dict)
    # Annual, in the source's own currency (Adzuna/RemoteOK both report
    # these when a listing states a figure at all — neither guarantees it).
    # None means "not stated", not "zero".
    salary_min: float | None = None
    salary_max: float | None = None
    match_score: float = 0.0
    match_reasons: tuple[str, ...] = ()
    # new -> reviewed -> (dismissed | applied). Set by the person, through the
    # UI; never touched by the pipeline once past "new".
    status: str = "new"

    @property
    def key(self) -> tuple[str, str]:
        return (self.source, self.external_id)

    def to_dict(self) -> dict[str, Any]:
        return {
            "source": self.source,
            "external_id": self.external_id,
            "title": self.title,
            "company": self.company,
            "location": self.location,
            "url": self.url,
            "description": self.description,
            "posted_date": self.posted_date.isoformat() if self.posted_date else None,
            "fetched_at": self.fetched_at.isoformat(),
            "raw_payload": self.raw_payload,
            "salary_min": self.salary_min,
            "salary_max": self.salary_max,
            "match_score": self.match_score,
            "match_reasons": list(self.match_reasons),
            "status": self.status,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> JobListing:
        return cls(
            source=d["source"],
            external_id=d["external_id"],
            title=d.get("title", ""),
            company=d.get("company", ""),
            location=d.get("location", ""),
            url=d.get("url", ""),
            description=d.get("description", ""),
            posted_date=_date_or_none(d.get("posted_date")),
            fetched_at=datetime.fromisoformat(d["fetched_at"]),
            raw_payload=d.get("raw_payload", {}),
            salary_min=d.get("salary_min"),
            salary_max=d.get("salary_max"),
            match_score=d.get("match_score", 0.0),
            match_reasons=tuple(d.get("match_reasons", ())),
            status=d.get("status", "new"),
        )


@dataclass(frozen=True)
class MarketInsights:
    """What the accumulated job-listing corpus says about the market."""

    generated_at: datetime
    top_skills: tuple[tuple[str, int], ...] = ()
    top_titles: tuple[tuple[str, int], ...] = ()
    listing_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at": self.generated_at.isoformat(),
            "top_skills": [list(pair) for pair in self.top_skills],
            "top_titles": [list(pair) for pair in self.top_titles],
            "listing_count": self.listing_count,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> MarketInsights:
        return cls(
            generated_at=datetime.fromisoformat(d["generated_at"]),
            top_skills=tuple((s, c) for s, c in d.get("top_skills", ())),
            top_titles=tuple((s, c) for s, c in d.get("top_titles", ())),
            listing_count=d.get("listing_count", 0),
        )


@dataclass(frozen=True)
class AdvancementGuidance:
    """The LLM-synthesized gap analysis, cached rather than regenerated per view."""

    generated_at: datetime
    skill_gaps: tuple[str, ...] = ()
    suggested_next_roles: tuple[str, ...] = ()
    rationale: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at": self.generated_at.isoformat(),
            "skill_gaps": list(self.skill_gaps),
            "suggested_next_roles": list(self.suggested_next_roles),
            "rationale": self.rationale,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> AdvancementGuidance:
        return cls(
            generated_at=datetime.fromisoformat(d["generated_at"]),
            skill_gaps=tuple(d.get("skill_gaps", ())),
            suggested_next_roles=tuple(d.get("suggested_next_roles", ())),
            rationale=d.get("rationale", ""),
        )


@dataclass(frozen=True)
class JobsDocument:
    """Everything the daily pipeline produces: listings, insights, guidance."""

    listings: tuple[JobListing, ...] = ()
    insights: MarketInsights | None = None
    guidance: AdvancementGuidance | None = None

    def with_listings(self, listings: tuple[JobListing, ...]) -> JobsDocument:
        return replace(self, listings=listings)

    def with_insights(self, insights: MarketInsights) -> JobsDocument:
        return replace(self, insights=insights)

    def with_guidance(self, guidance: AdvancementGuidance) -> JobsDocument:
        return replace(self, guidance=guidance)

    def with_listing_status(self, key: tuple[str, str], status: str) -> JobsDocument:
        """Return a copy with one listing's status changed, by (source, external_id)."""
        updated = tuple(
            replace(listing, status=status) if listing.key == key else listing
            for listing in self.listings
        )
        return replace(self, listings=updated)

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": SCHEMA_VERSION,
            "listings": [listing.to_dict() for listing in self.listings],
            "insights": self.insights.to_dict() if self.insights else None,
            "guidance": self.guidance.to_dict() if self.guidance else None,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> JobsDocument:
        insights = d.get("insights")
        guidance = d.get("guidance")
        return cls(
            listings=tuple(JobListing.from_dict(j) for j in d.get("listings", ())),
            insights=MarketInsights.from_dict(insights) if insights else None,
            guidance=AdvancementGuidance.from_dict(guidance) if guidance else None,
        )

    @classmethod
    def from_json(cls, raw: str) -> JobsDocument:
        return cls.from_dict(json.loads(raw))
